"""
Django settings for library_management project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

try:
    import pyodbc
except ImportError:  # pragma: no cover - dependency is installed in runtime environments
    pyodbc = None


def _get_env(name, default=None):
    value = os.getenv(name)
    return default if value is None else value


def _get_database_options():
    explicit_driver = _get_env('DB_DRIVER')
    available_drivers = []

    if pyodbc is not None:
        try:
            available_drivers = pyodbc.drivers()
        except Exception:
            available_drivers = []

    preferred_drivers = [
        'ODBC Driver 18 for SQL Server',
        'ODBC Driver 17 for SQL Server',
        'SQL Server Native Client 11.0',
        'SQL Server Native Client 10.0',
    ]

    unsupported_drivers = {'SQL Server'}

    if explicit_driver in unsupported_drivers:
        raise ImproperlyConfigured(
            "DB_DRIVER='SQL Server' is not supported by mssql-django for this project. "
            "Install ODBC Driver 18 or 17 for SQL Server, then set DB_DRIVER accordingly."
        )

    if explicit_driver:
        driver = explicit_driver
    else:
        driver = next(
            (candidate for candidate in preferred_drivers if candidate in available_drivers),
            None,
        )

    if driver is None:
        raise ImproperlyConfigured(
            "No supported SQL Server ODBC driver was found. Install 'ODBC Driver 18 for SQL Server' "
            "or 'ODBC Driver 17 for SQL Server', or run the app via Docker where the driver is bundled."
        )

    extra_params = _get_env('DB_EXTRA_PARAMS')
    if extra_params is None and driver.startswith('ODBC Driver '):
        extra_params = 'TrustServerCertificate=yes'

    options = {
        'driver': driver,
    }

    if extra_params:
        options['extra_params'] = extra_params

    return options


DATABASE_OPTIONS = _get_database_options()
DATABASE_HOST = _get_env('DB_HOST', '127.0.0.1')
DATABASE_PORT = _get_env('DB_PORT', '1433')

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent


# Static files
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=ya&(561qd!lf4pjy#o@nr*^+n@^sq=7hfclzx*@w42(w@am*^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'library_management_system',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'library_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'library_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': os.getenv('DB_NAME', 'QLS'),
        'USER': os.getenv('DB_USER', 'sa'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'YourStrong@Pass123'),
        'HOST': DATABASE_HOST,
        'PORT': DATABASE_PORT,
        'OPTIONS': DATABASE_OPTIONS,
    }
}

# Keep auth/session flows lightweight for the demo app so the project
# doesn't depend on creating Django's default DB tables before first run.
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
