IF DB_ID('QLS') IS NULL
BEGIN
    CREATE DATABASE QLS;
END;
GO

USE QLS;
GO

IF OBJECT_ID('dbo.THELOAI', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.THELOAI (
        THELOAIID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        TENTHELOAI NVARCHAR(255) NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.TACGIA', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TACGIA (
        TACGIAID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        TENTACGIA NVARCHAR(255) NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.NHANVIEN', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.NHANVIEN (
        NHANVIENID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        MANV NVARCHAR(50) NOT NULL UNIQUE,
        HOTEN NVARCHAR(255) NOT NULL,
        EMAIL NVARCHAR(100) NULL,
        SDT NVARCHAR(10) NULL,
        CHUCVU NVARCHAR(100) NULL,
        LUONG DECIMAL(10,2) NULL,
        NGAYVAOLAM DATE NULL
    );
END;
GO

IF OBJECT_ID('dbo.SINHVIEN', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SINHVIEN (
        SINHVIENID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        MSSV NVARCHAR(50) NOT NULL UNIQUE,
        HOTEN NVARCHAR(255) NOT NULL,
        EMAIL NVARCHAR(50) NULL,
        SDT NVARCHAR(10) NULL,
        LOPHOC NVARCHAR(50) NOT NULL
    );
END;
GO

IF OBJECT_ID('dbo.SACH', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.SACH (
        SACHID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        TENSACH NVARCHAR(255) NOT NULL,
        NAMXUATBAN INT NULL,
        NHAXUATBAN NVARCHAR(255) NULL,
        SOLUONG INT NULL,
        THELOAIID INT NOT NULL,
        TACGIAID INT NOT NULL,
        CONSTRAINT FK_SACH_THELOAI FOREIGN KEY (THELOAIID) REFERENCES dbo.THELOAI (THELOAIID),
        CONSTRAINT FK_SACH_TACGIA FOREIGN KEY (TACGIAID) REFERENCES dbo.TACGIA (TACGIAID)
    );
END;
GO

IF OBJECT_ID('dbo.TAIKHOAN', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TAIKHOAN (
        TAIKHOANID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        USERNAME NVARCHAR(50) NOT NULL UNIQUE,
        MATKHAU NVARCHAR(255) NOT NULL,
        VAITRO NVARCHAR(50) NOT NULL,
        NHANVIENID INT NOT NULL,
        CONSTRAINT FK_TAIKHOAN_NHANVIEN FOREIGN KEY (NHANVIENID) REFERENCES dbo.NHANVIEN (NHANVIENID)
    );
END;
GO

IF OBJECT_ID('dbo.MUONSACH', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.MUONSACH (
        MUONSACHID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        SACHID INT NOT NULL,
        SINHVIENID INT NOT NULL,
        CONSTRAINT FK_MUONSACH_SACH FOREIGN KEY (SACHID) REFERENCES dbo.SACH (SACHID),
        CONSTRAINT FK_MUONSACH_SINHVIEN FOREIGN KEY (SINHVIENID) REFERENCES dbo.SINHVIEN (SINHVIENID)
    );
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THELOAI WHERE TENTHELOAI = N'Cong nghe')
BEGIN
    INSERT INTO dbo.THELOAI (TENTHELOAI) VALUES (N'Cong nghe');
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.THELOAI WHERE TENTHELOAI = N'Khoa hoc')
BEGIN
    INSERT INTO dbo.THELOAI (TENTHELOAI) VALUES (N'Khoa hoc');
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.TACGIA WHERE TENTACGIA = N'Lap trinh Viet')
BEGIN
    INSERT INTO dbo.TACGIA (TENTACGIA) VALUES (N'Lap trinh Viet');
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.TACGIA WHERE TENTACGIA = N'Nguyen Nhat Minh')
BEGIN
    INSERT INTO dbo.TACGIA (TENTACGIA) VALUES (N'Nguyen Nhat Minh');
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.NHANVIEN WHERE MANV = N'NV001')
BEGIN
    INSERT INTO dbo.NHANVIEN (MANV, HOTEN, EMAIL, SDT, CHUCVU, LUONG, NGAYVAOLAM)
    VALUES (N'NV001', N'Admin Demo', N'admin@example.com', N'0900000001', N'Quan tri', 12000000, '2026-01-01');
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.SINHVIEN WHERE MSSV = N'SV001')
BEGIN
    INSERT INTO dbo.SINHVIEN (MSSV, HOTEN, EMAIL, SDT, LOPHOC)
    VALUES (N'SV001', N'Nguyen Van A', N'sv001@example.com', N'0911111111', N'CNTT1');
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.TAIKHOAN WHERE USERNAME = N'admin')
BEGIN
    INSERT INTO dbo.TAIKHOAN (USERNAME, MATKHAU, VAITRO, NHANVIENID)
    SELECT N'admin', N'123456', N'admin', NHANVIENID
    FROM dbo.NHANVIEN
    WHERE MANV = N'NV001';
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.SACH WHERE TENSACH = N'Django Web')
BEGIN
    INSERT INTO dbo.SACH (TENSACH, NAMXUATBAN, NHAXUATBAN, SOLUONG, THELOAIID, TACGIAID)
    SELECT N'Django Web', 2025, N'NXB Tre', 10, tl.THELOAIID, tg.TACGIAID
    FROM dbo.THELOAI tl
    CROSS JOIN dbo.TACGIA tg
    WHERE tl.TENTHELOAI = N'Cong nghe' AND tg.TENTACGIA = N'Lap trinh Viet';
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.SACH WHERE TENSACH = N'SQL Server Co Ban')
BEGIN
    INSERT INTO dbo.SACH (TENSACH, NAMXUATBAN, NHAXUATBAN, SOLUONG, THELOAIID, TACGIAID)
    SELECT N'SQL Server Co Ban', 2024, N'NXB Giao Duc', 6, tl.THELOAIID, tg.TACGIAID
    FROM dbo.THELOAI tl
    CROSS JOIN dbo.TACGIA tg
    WHERE tl.TENTHELOAI = N'Cong nghe' AND tg.TENTACGIA = N'Nguyen Nhat Minh';
END;
GO

IF NOT EXISTS (SELECT 1 FROM dbo.MUONSACH)
BEGIN
    INSERT INTO dbo.MUONSACH (SACHID, SINHVIENID)
    SELECT TOP 1 s.SACHID, sv.SINHVIENID
    FROM dbo.SACH s
    CROSS JOIN dbo.SINHVIEN sv
    WHERE s.TENSACH = N'Django Web' AND sv.MSSV = N'SV001';
END;
GO
