USE QLS;
GO

-- Create PHIEUMUON table
IF OBJECT_ID('dbo.PHIEUMUON', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PHIEUMUON (
        PHIEUMUONID INT IDENTITY(1,1) PRIMARY KEY,
        SINHVIENID INT NOT NULL,
        NHANVIENID INT NOT NULL,
        NGAYMUON DATETIME DEFAULT GETDATE(),
        NGAYTRA DATE NOT NULL,
        TRANGTHAI NVARCHAR(50) DEFAULT N'Đang mượn',
        FOREIGN KEY (SINHVIENID) REFERENCES dbo.SINHVIEN(SINHVIENID),
        FOREIGN KEY (NHANVIENID) REFERENCES dbo.NHANVIEN(NHANVIENID)
    );
END
GO

-- Create CT_PHIEUMUON table
IF OBJECT_ID('dbo.CT_PHIEUMUON', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.CT_PHIEUMUON (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        PHIEUMUONID INT NOT NULL,
        SACHID INT NOT NULL,
        SOLUONG INT NOT NULL,
        FOREIGN KEY (PHIEUMUONID) REFERENCES dbo.PHIEUMUON(PHIEUMUONID),
        FOREIGN KEY (SACHID) REFERENCES dbo.SACH(SACHID)
    );
END
GO

-- SP_MUONSACH
IF OBJECT_ID('dbo.SP_MUONSACH', 'P') IS NOT NULL DROP PROCEDURE dbo.SP_MUONSACH;
GO
CREATE PROCEDURE dbo.SP_MUONSACH
    @SINHVIENID INT,
    @NHANVIENID INT,
    @NGAYTRA DATE
AS
BEGIN
    INSERT INTO dbo.PHIEUMUON (SINHVIENID, NHANVIENID, NGAYMUON, NGAYTRA, TRANGTHAI)
    VALUES (@SINHVIENID, @NHANVIENID, GETDATE(), @NGAYTRA, N'Đang mượn');
    SELECT SCOPE_IDENTITY() AS PHIEUMUONID;
END
GO

-- SP_THEM_SACH_VAO_PHIEU
IF OBJECT_ID('dbo.SP_THEM_SACH_VAO_PHIEU', 'P') IS NOT NULL DROP PROCEDURE dbo.SP_THEM_SACH_VAO_PHIEU;
GO
CREATE PROCEDURE dbo.SP_THEM_SACH_VAO_PHIEU
    @PHIEUMUONID INT,
    @SACHID INT,
    @SOLUONG INT
AS
BEGIN
    INSERT INTO dbo.CT_PHIEUMUON (PHIEUMUONID, SACHID, SOLUONG)
    VALUES (@PHIEUMUONID, @SACHID, @SOLUONG);
    
    -- Giảm số lượng sách
    UPDATE dbo.SACH
    SET SOLUONG = SOLUONG - @SOLUONG
    WHERE SACHID = @SACHID;
END
GO

-- SP_TRASACH
IF OBJECT_ID('dbo.SP_TRASACH', 'P') IS NOT NULL DROP PROCEDURE dbo.SP_TRASACH;
GO
CREATE PROCEDURE dbo.SP_TRASACH
    @PHIEUMUONID INT
AS
BEGIN
    UPDATE dbo.PHIEUMUON
    SET TRANGTHAI = N'Đã trả'
    WHERE PHIEUMUONID = @PHIEUMUONID;

    -- Hoàn lại số lượng sách
    UPDATE S
    SET S.SOLUONG = S.SOLUONG + CT.SOLUONG
    FROM dbo.SACH S
    JOIN dbo.CT_PHIEUMUON CT ON S.SACHID = CT.SACHID
    WHERE CT.PHIEUMUONID = @PHIEUMUONID;
END
GO

-- SP_THEMSACH
IF OBJECT_ID('dbo.SP_THEMSACH', 'P') IS NOT NULL DROP PROCEDURE dbo.SP_THEMSACH;
GO
CREATE PROCEDURE dbo.SP_THEMSACH
    @TENSACH NVARCHAR(255),
    @NAMXUATBAN INT,
    @NHAXUATBAN NVARCHAR(255),
    @SOLUONG INT,
    @THELOAIID INT,
    @TACGIAID INT
AS
BEGIN
    INSERT INTO dbo.SACH (TENSACH, NAMXUATBAN, NHAXUATBAN, SOLUONG, THELOAIID, TACGIAID)
    VALUES (@TENSACH, @NAMXUATBAN, @NHAXUATBAN, @SOLUONG, @THELOAIID, @TACGIAID);
END
GO

-- SP_CAPNHATSACH
IF OBJECT_ID('dbo.SP_CAPNHATSACH', 'P') IS NOT NULL DROP PROCEDURE dbo.SP_CAPNHATSACH;
GO
CREATE PROCEDURE dbo.SP_CAPNHATSACH
    @SACHID INT,
    @TENSACH NVARCHAR(255),
    @NAMXUATBAN INT,
    @NHAXUATBAN NVARCHAR(255),
    @SOLUONG INT
AS
BEGIN
    UPDATE dbo.SACH
    SET TENSACH = @TENSACH, NAMXUATBAN = @NAMXUATBAN, NHAXUATBAN = @NHAXUATBAN, SOLUONG = @SOLUONG
    WHERE SACHID = @SACHID;
END
GO

-- SP_XOASACH
IF OBJECT_ID('dbo.SP_XOASACH', 'P') IS NOT NULL DROP PROCEDURE dbo.SP_XOASACH;
GO
CREATE PROCEDURE dbo.SP_XOASACH
    @SACHID INT
AS
BEGIN
    DELETE FROM dbo.SACH WHERE SACHID = @SACHID;
END
GO
